/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author CAAG-SL-LAB8
 */
public class ventanaPantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPantallaPrincipal
     */
    public ventanaPantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPagos = new javax.swing.JButton();
        btnAspirante = new javax.swing.JButton();
        btnCalificaciones = new javax.swing.JButton();
        btnConcentrado = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        itemConsultarAlumno = new javax.swing.JMenuItem();
        itemModificarAlumno = new javax.swing.JMenuItem();
        itemRegistrarAlumno = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();
        itemConsultar = new javax.swing.JMenuItem();
        itemIngresar = new javax.swing.JMenuItem();
        itemModificar = new javax.swing.JMenuItem();
        itemEliminar = new javax.swing.JMenuItem();
        menuPlan = new javax.swing.JMenu();
        menuCursos = new javax.swing.JMenu();
        itemNuevoCurso = new javax.swing.JMenuItem();
        itemModificarCurso = new javax.swing.JMenuItem();
        itemMenuMaterias = new javax.swing.JMenu();
        itemNuevaMateria = new javax.swing.JMenuItem();
        menuCorreo = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(3, 147, 207));

        jPanel2.setBackground(new java.awt.Color(250, 187, 2));

        btnPagos.setBackground(new java.awt.Color(177, 26, 81));
        btnPagos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPagos.setForeground(new java.awt.Color(250, 250, 250));
        btnPagos.setText("Pagos");

        btnAspirante.setBackground(new java.awt.Color(177, 26, 81));
        btnAspirante.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAspirante.setForeground(new java.awt.Color(255, 255, 255));
        btnAspirante.setText("Aspirantes");
        btnAspirante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAspiranteActionPerformed(evt);
            }
        });

        btnCalificaciones.setBackground(new java.awt.Color(177, 26, 81));
        btnCalificaciones.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCalificaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnCalificaciones.setText("Calificaciones");

        btnConcentrado.setBackground(new java.awt.Color(177, 26, 81));
        btnConcentrado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConcentrado.setForeground(new java.awt.Color(255, 255, 255));
        btnConcentrado.setText("Concentrado");

        btnAcercaDe.setBackground(new java.awt.Color(177, 26, 81));
        btnAcercaDe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAcercaDe.setForeground(new java.awt.Color(255, 255, 255));
        btnAcercaDe.setText("Acerca de");

        jLabel1.setText("Inmus V1.0.0");

        jPanel3.setBackground(new java.awt.Color(177, 26, 81));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAspirante, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConcentrado, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnAspirante, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnConcentrado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 638, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 910, 500));

        menuAlumnos.setText("Alumnos");

        itemConsultarAlumno.setText("Consultar");
        menuAlumnos.add(itemConsultarAlumno);

        itemModificarAlumno.setText("Modificar");
        menuAlumnos.add(itemModificarAlumno);

        itemRegistrarAlumno.setText("Nuevo");
        menuAlumnos.add(itemRegistrarAlumno);

        jMenuBar1.add(menuAlumnos);

        menuEmpleados.setText("Empleados");

        itemConsultar.setText("Consultar");
        menuEmpleados.add(itemConsultar);

        itemIngresar.setText("Ingresar");
        itemIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIngresarActionPerformed(evt);
            }
        });
        menuEmpleados.add(itemIngresar);

        itemModificar.setText("Modificar");
        menuEmpleados.add(itemModificar);

        itemEliminar.setText("Eliminar");
        menuEmpleados.add(itemEliminar);

        jMenuBar1.add(menuEmpleados);

        menuPlan.setText("Plan de Estudios");

        menuCursos.setText("Cursos");

        itemNuevoCurso.setText("Nuevo Curso");
        menuCursos.add(itemNuevoCurso);

        itemModificarCurso.setText("Modificar Curso");
        menuCursos.add(itemModificarCurso);

        menuPlan.add(menuCursos);

        itemMenuMaterias.setText("Materias");

        itemNuevaMateria.setText("jMenuItem3");
        itemMenuMaterias.add(itemNuevaMateria);

        menuPlan.add(itemMenuMaterias);

        jMenuBar1.add(menuPlan);

        menuCorreo.setText("Correo");
        jMenuBar1.add(menuCorreo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAspiranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAspiranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAspiranteActionPerformed

    private void itemIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAcercaDe;
    public javax.swing.JButton btnAspirante;
    public javax.swing.JButton btnCalificaciones;
    public javax.swing.JButton btnConcentrado;
    public javax.swing.JButton btnPagos;
    public javax.swing.JMenuItem itemConsultar;
    public javax.swing.JMenuItem itemConsultarAlumno;
    public javax.swing.JMenuItem itemEliminar;
    public javax.swing.JMenuItem itemIngresar;
    public javax.swing.JMenu itemMenuMaterias;
    public javax.swing.JMenuItem itemModificar;
    public javax.swing.JMenuItem itemModificarAlumno;
    public javax.swing.JMenuItem itemModificarCurso;
    public javax.swing.JMenuItem itemNuevaMateria;
    public javax.swing.JMenuItem itemNuevoCurso;
    public javax.swing.JMenuItem itemRegistrarAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JMenu menuAlumnos;
    public javax.swing.JMenu menuCorreo;
    public javax.swing.JMenu menuCursos;
    public javax.swing.JMenu menuEmpleados;
    public javax.swing.JMenu menuPlan;
    // End of variables declaration//GEN-END:variables
}
